# Setup
title:        xxx是女孩子
tagline:      关于她们。。。
baseurl:      ""
paginate:     1
locale:       "zh"

# About/contact
author:        
  name:       xxx-is-a-girl
  url:        http://github.com/is-a-girl

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
